---
title: IconShop Home
baseurl: "/"
permalink: "/:title/"
palette: orange
header:
  title: IconShop
  logo_img: "/images/AppIcon_512x512@1x.png"
  has_nav: true
  nav_links: []
footer:
  logo_img: images/logo_alt.png
  tagline: ''
  has_nav: true
  nav_title: Company
  nav_links: []
  has_social: false
  social_title: Community
  social_links: []
  has_subscribe: false
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Aben.io. All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
