---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5e9a88df0be711001ab87a19/webhook/forestry
sections:
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle update --bundler;bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --incremental
    --future --port 8080 --host 0.0.0.0 -d _site
